version: '2'

services:
  seed:
    image: lachatak/server:1.0.0
    depends_on:
      - cassandra
    ports:
      - '1600:1600'
      - '8080:8080'
    environment:
      CLUSTER_PORT: 1600
      CLUSTER_IP: seed
      SEED_PORT_1600_TCP_ADDR: seed
      CASSANDRA_IP: cassandra
  s1:
    image: lachatak/server:1.0.0
    depends_on:
      - cassandra
      - seed
    ports:
      - '1601:1601'
    environment:
      CLUSTER_PORT: 1601
      CLUSTER_IP: s1
      SEED_PORT_1600_TCP_ADDR: seed
      CASSANDRA_IP: cassandra
  s2:
    image: lachatak/server:1.0.0
    depends_on:
      - cassandra
      - seed
    ports:
      - '1602:1602'
    environment:
      CLUSTER_PORT: 1602
      CLUSTER_IP: s2
      SEED_PORT_1600_TCP_ADDR: seed
      CASSANDRA_IP: cassandra

  cassandra:
    image: cassandra
    volumes:
      - ./server/datadir:/var/lib/cassandra
    environment:
      - CASSANDRA_DC=datacenter1
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"