version: '2'

services:
  server1:
    image: relateiq/oracle-java8
    volumes:
      - ./shared:/shared
    environment:
      - LOOPBACK=localhost
    entrypoint:
      - /bin/sh
      - ./shared/start.sh
    ports:
      - '8000:8000'

  server2:
    image: relateiq/oracle-java8
    volumes:
      - ./shared:/shared
    environment:
      - LOOPBACK=localhost
    entrypoint:
      - /bin/sh
      - ./shared/start.sh
    ports:
      - '8000:8000'

  cassandra:
    image: cassandra
    volumes:
      - ./datadir:/var/lib/cassandra
    environment:
      - CASSANDRA_DC=datacenter1
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"